function esn=initESN(K,L,M) % nIn, nNodes, nOut
% function to initialize the ESN with fixed parameters
%
% ________________________________________________________________________
%
% This file is released under the terms of the GNU General Public License,
% version 3. See http://www.gnu.org/licenses/gpl.html
%
%                                           (c) Andreas Daffertshofer 2021
% ________________________________________________________________________
%
% See also initializeESN

checkESNtoolbox;

esn=initializeESN(K,L,M, ...
    'spectralRadius',0.5, ...
    'inputScaling',[0.1;0.5*ones(K,1)], ...
    'inputShift',0*rand(K+1,1), ...
    'teacherScaling',0.5*ones(M,1), ...
    'teacherShift',zeros(M,1), ...
    'feedbackScaling',0, ...
    'type','leaky_esn', ...
    'timeConstants',1*ones(L,1), ...
    'leakage',0.5, ...
    'noiseLevel',1e-3, ...
    'learningMode', 'offline_singleTimeSeries' ...
    );

end

%% _ EOF__________________________________________________________________